export const filmsCopy = {
  list: {
    titleId: "films-heading",
    title: "Films",
    description:
      "Films logged in the clamari journal — watched, rewatched, and still on the list.",
    listAriaLabel: "Film entries",
    empty: "No films yet.",
    noResults: "No films match these filters.",
    summary: "{watched} watched · {watchlist} on the list · {total} total",
    hero: {
      titleId: "films-hero-heading",
      title: "Films",
      sentinelId: "films-catalog-hero",
      image: {
        src: "/images/films/poor-things-hero.webp",
        alt: "Poor Things",
      },
    },
  },
  detail: {
    titleId: "film-detail-heading",
    heroSentinelId: "film-detail-hero",
    backLabel: "All films",
    backHref: "/films",
    metadata: {
      heading: "About the film",
      headingId: "film-metadata-heading",
      unresolved:
        "This entry is not linked to TMDB yet. Poster and credits will appear after enrichment.",
      unavailable:
        "TMDB metadata could not be loaded. Personal journal details below are still available.",
      originalTitle: "Original title",
      runtime: "Runtime",
      genres: "Genres",
      synopsis: "Synopsis",
      directors: "Director",
      writers: "Writers",
      cast: "Cast",
      castHeadingId: "film-cast-heading",
      countries: "Country",
      languages: "Language",
      trailer: "Trailer",
      trailerCta: "Watch trailer",
      noSynopsis: "No synopsis available.",
      noCast: "No cast listed.",
      castShowMore: "See more",
      castShowLess: "See less",
    },
    journal: {
      heading: "In your journal",
      headingId: "film-journal-heading",
      status: "Status",
      rating: "Your rating",
      favorite: "Favorite",
      tags: "Tags",
      watchLocation: "Watched at",
      streamingService: "Streamed on",
      noRating: "Not rated",
      noTags: "No tags",
    },
    viewings: {
      heading: "Viewing history",
      headingId: "film-viewings-heading",
      countOne: "1 viewing",
      countMany: "{count} viewings",
      countNone: "No viewings logged",
      first: "First viewing",
      rewatch: "Rewatch",
      empty: "No watch dates recorded yet.",
    },
    review: {
      heading: "Review",
      headingId: "film-review-heading",
      empty: "No review yet.",
      pending: "Review on the way.",
    },
    meta: {
      descriptionFallback: "Personal journal entry for {title}.",
      descriptionFromSynopsis: "{synopsis}",
    },
  },
} as const;

export type FilmsCopy = typeof filmsCopy;
