export const seriesCopy = {
  list: {
    titleId: "series-heading",
    title: "Series",
    listAriaLabel: "Series entries",
    empty: "No series yet.",
    noResults: "No series match these filters.",
    summary:
      "{total} series · {episodes} episodes · {completed} completed · {watching} watching",
    hero: {
      titleId: "series-hero-heading",
      title: "Series",
      sentinelId: "series-catalog-hero",
      image: {
        src: "/images/series/fleabag-hero.webp",
        alt: "Fleabag",
      },
    },
  },
  detail: {
    titleId: "series-detail-heading",
    heroSentinelId: "series-detail-hero",
    backLabel: "All series",
    backHref: "/series",
    metadata: {
      heading: "About the series",
      headingId: "series-metadata-heading",
      unresolved:
        "This entry is not linked to TMDB yet. Poster and credits will appear after enrichment.",
      unavailable:
        "TMDB metadata could not be loaded. Personal journal details below are still available.",
      originalTitle: "Original title",
      genres: "Genres",
      synopsis: "Synopsis",
      creators: "Created by",
      writers: "Writers",
      cast: "Cast",
      castHeadingId: "series-cast-heading",
      countries: "Country",
      languages: "Language",
      productionStatus: "Show status",
      trailer: "Trailer",
      trailerCta: "Watch trailer",
      noSynopsis: "No synopsis available.",
      noCast: "No cast listed.",
      castShowMore: "See more",
      castShowLess: "See less",
    },
    journal: {
      heading: "In your journal",
      headingId: "series-journal-heading",
      status: "Status",
      rating: "Your rating",
      favorite: "Favorite",
      started: "Started",
      finished: "Finished",
      watchedEpisodes: "Episodes watched",
      watchedTime: "Watched time",
      progress: "Progress",
      nextEpisode: "Up next",
      noRating: "Not rated",
    },
    seasons: {
      heading: "Seasons",
      headingId: "series-seasons-heading",
      empty: "No season metadata available yet.",
      specials: "Specials",
      seasonTitle: "Season {number}",
      progress: "{watched} of {total} watched",
      episodeFallback: "Episode {number}",
      nextBadge: "Next",
      watched: "Watched",
      unwatched: "Not watched",
      airDate: "Aired",
      runtime: "Runtime",
    },
    review: {
      heading: "Review",
      headingId: "series-review-heading",
      empty: "No review yet.",
      pending: "Review on the way.",
    },
    meta: {
      descriptionFallback: "Personal journal entry for {title}.",
      descriptionFromSynopsis: "{synopsis}",
    },
  },
} as const;

export type SeriesCopy = typeof seriesCopy;
