export const catalogCopyPt = {
  toolbar: {
    searchAriaLabel: "Buscar no catálogo",
    searchPlaceholder: {
      films: "Buscar filmes",
      series: "Buscar séries",
      books: "Buscar livros",
      all: "Buscar entradas",
    },
    filtersLabel: "Status",
    filtersAriaLabel: "Filtrar por status",
    filtersAll: "Todos",
    yearLabel: "Ano",
    yearAriaLabel: "Filtrar pelo ano em que terminou",
    yearAll: "Todos os anos",
    reviewLabel: "Resenha",
    reviewAriaLabel: "Mostrar só entradas com resenha",
    favoriteLabel: "Favoritos",
    favoriteAriaLabel: "Mostrar só favoritos",
    sortLabel: "Ordenar",
    sortAriaLabel: "Ordenar catálogo",
    sortOptions: {
      default: "Adicionados recentemente",
      titleAsc: "Título A–Z",
      titleDesc: "Título Z–A",
      dateNewest: "Atividade mais recente",
      dateOldest: "Atividade mais antiga",
      yearNewest: "Lançamento mais novo",
      yearOldest: "Lançamento mais antigo",
      ratingHigh: "Maior nota",
      ratingLow: "Menor nota",
    },
    viewCardsLabel: "Vista em cartões",
    viewListLabel: "Vista em lista",
    viewCardsAriaLabel: "Mudar para vista em cartões",
    viewListAriaLabel: "Mudar para vista em lista",
    clearAllLabel: "Limpar",
    clearAllAriaLabel: "Limpar busca, filtros e ordenação",
    seeAll: "Ver tudo",
  },
  card: {
    favorite: "Favorito",
    notFavorite: "Não favorito",
    withReview: "Com resenha",
    noReview: "Sem resenha",
    watchedOn: "Assistido em {date}",
    addedOn: "Adicionado em {date}",
    startedOn: "Começou em {date}",
    finishedOn: "Terminou em {date}",
    noActivityDate: "Sem data registrada",
    episodeCount: "{count} ep.",
    pageCount: "{count} páginas",
  },
  status: {
    films: {
      watched: "Assistido",
      rewatch: "Reassistido",
      watchlist: "Quero assistir",
    },
    series: {
      watchlist: "Quero assistir",
      watching: "Assistindo",
      paused: "Pausada",
      completed: "Completa",
      abandoned: "Abandonada",
    },
    books: {
      "want-to-read": "Quero ler",
      reading: "Lendo",
      paused: "Pausado",
      finished: "Lido",
      abandoned: "Abandonado",
    },
  },
  statusHint: {
    films: {
      watched: "Registrado com uma data de exibição.",
      rewatch: "Registrado com duas ou mais datas de exibição.",
      watchlist: "Na lista. Ainda não há data de exibição.",
    },
    series: {
      watchlist: "Na lista. Ainda não há episódio registrado.",
      watching:
        "Já começou e está em acompanhamento agora. Ainda não terminou.",
      paused:
        "Já começou e está em espera. Não terminou — e não foi desistida.",
      completed:
        "Todos os episódios lançados já foram assistidos. Cada episódio conta uma vez.",
      abandoned: "Já começou e foi desistida. Não volta para ela.",
    },
    books: {
      "want-to-read": "Na lista. Ainda não há páginas registradas.",
      reading: "Já começou e está sendo lido agora. Ainda não terminou.",
      paused:
        "Já começou e está em espera. Não terminou — e não foi desistido.",
      finished: "Chegou à última página.",
      abandoned: "Já começou e foi desistido. Não volta para ele.",
    },
  },
} as const;
