export const filmsCopyPt = {
  list: {
    titleId: "films-heading",
    title: "Filmes",
    description:
      "Filmes que assisti, reassisti e quero ver — catálogo pessoal com notas, favoritos e resenhas no clamari journal.",
    listAriaLabel: "Entradas de filmes",
    empty: "Nenhum filme ainda.",
    noResults: "Nenhum filme combina com esses filtros.",
    summary: "{watched} assistidos · {watchlist} na lista · {total} no total",
    hero: {
      titleId: "films-hero-heading",
      title: "Filmes",
      sentinelId: "films-catalog-hero",
      image: {
        src: "/images/films/poor-things-hero.webp",
        alt: "Pobres Criaturas",
      },
    },
  },
  detail: {
    titleId: "film-detail-heading",
    heroSentinelId: "film-detail-hero",
    backLabel: "Todos os filmes",
    backHref: "/films",
    metadata: {
      heading: "Sobre o filme",
      headingId: "film-metadata-heading",
      unresolved:
        "Esta entrada ainda não está ligada ao TMDB. Pôster e créditos aparecem depois do enriquecimento.",
      unavailable:
        "Não foi possível carregar os metadados do TMDB. Os dados pessoais do diário continuam abaixo.",
      originalTitle: "Título original",
      runtime: "Duração",
      genres: "Gêneros",
      synopsis: "Sinopse",
      directors: "Direção",
      writers: "Roteiro",
      cast: "Elenco",
      castHeadingId: "film-cast-heading",
      countries: "País",
      languages: "Idioma",
      trailer: "Trailer",
      trailerCta: "Assistir ao trailer",
      noSynopsis: "Sem sinopse disponível.",
      noCast: "Sem elenco listado.",
      castShowMore: "Ver mais",
      castShowLess: "Ver menos",
    },
    journal: {
      heading: "No diário",
      headingId: "film-journal-heading",
      status: "Status",
      rating: "Sua nota",
      favorite: "Favorito",
      tags: "Tags",
      watchLocation: "Assistido em",
      streamingService: "Streaming",
      noRating: "Sem nota",
      noTags: "Sem tags",
    },
    viewings: {
      heading: "Histórico de sessões",
      headingId: "film-viewings-heading",
      countOne: "1 sessão",
      countMany: "{count} sessões",
      countNone: "Nenhuma sessão registrada",
      first: "Primeira sessão",
      rewatch: "Reassistido",
      empty: "Nenhuma data de sessão registrada ainda.",
    },
    review: {
      heading: "Resenha",
      headingId: "film-review-heading",
      empty: "Ainda sem resenha.",
      pending: "Resenha a caminho.",
    },
    meta: {
      descriptionFallback: "Entrada pessoal do diário sobre {title}.",
      descriptionFromSynopsis: "{synopsis}",
    },
  },
} as const;
