export const seriesCopyPt = {
  list: {
    titleId: "series-heading",
    title: "Séries",
    description:
      "Séries que acompanho, pausei e completei — catálogo pessoal com progresso, notas e resenhas no clamari journal.",
    listAriaLabel: "Entradas de séries",
    empty: "Nenhuma série ainda.",
    noResults: "Nenhuma série combina com esses filtros.",
    summary:
      "{total} séries · {episodes} episódios · {completed} completas · {watching} assistindo",
    hero: {
      titleId: "series-hero-heading",
      title: "Séries",
      sentinelId: "series-catalog-hero",
      image: {
        src: "/images/series/fleabag-hero.webp",
        alt: "Fleabag",
      },
    },
  },
  detail: {
    titleId: "series-detail-heading",
    heroSentinelId: "series-detail-hero",
    backLabel: "Todas as séries",
    backHref: "/series",
    metadata: {
      heading: "Sobre a série",
      headingId: "series-metadata-heading",
      unresolved:
        "Esta entrada ainda não está ligada ao TMDB. Pôster e créditos aparecem depois do enriquecimento.",
      unavailable:
        "Não foi possível carregar os metadados do TMDB. Os dados pessoais do diário continuam abaixo.",
      originalTitle: "Título original",
      genres: "Gêneros",
      synopsis: "Sinopse",
      creators: "Criação",
      writers: "Roteiro",
      cast: "Elenco",
      castHeadingId: "series-cast-heading",
      countries: "País",
      languages: "Idioma",
      productionStatus: "Status da série",
      trailer: "Trailer",
      trailerCta: "Assistir ao trailer",
      noSynopsis: "Sem sinopse disponível.",
      noCast: "Sem elenco listado.",
      castShowMore: "Ver mais",
      castShowLess: "Ver menos",
    },
    journal: {
      heading: "No diário",
      headingId: "series-journal-heading",
      status: "Status",
      rating: "Sua nota",
      favorite: "Favorito",
      started: "Começou",
      finished: "Terminou",
      watchedEpisodes: "Episódios assistidos",
      watchedTime: "Tempo assistido",
      progress: "Progresso",
      nextEpisode: "Próximo",
      noRating: "Sem nota",
    },
    seasons: {
      heading: "Temporadas",
      headingId: "series-seasons-heading",
      empty: "Metadados de temporada ainda indisponíveis.",
      specials: "Especiais",
      seasonTitle: "Temporada {number}",
      progress: "{watched} de {total} assistidos",
      episodeFallback: "Episódio {number}",
      nextBadge: "Próximo",
      watched: "Assistido",
      unwatched: "Não assistido",
      airDate: "Exibido",
      runtime: "Duração",
    },
    review: {
      heading: "Resenha",
      headingId: "series-review-heading",
      empty: "Ainda sem resenha.",
      pending: "Resenha a caminho.",
    },
    meta: {
      descriptionFallback: "Entrada pessoal do diário sobre {title}.",
      descriptionFromSynopsis: "{synopsis}",
    },
  },
} as const;
